// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: programdb.proto

#ifndef PROTOBUF_programdb_2eproto__INCLUDED
#define PROTOBUF_programdb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_programdb_2eproto();
void protobuf_AssignDesc_programdb_2eproto();
void protobuf_ShutdownFile_programdb_2eproto();

class SourceFileList;

// ===================================================================

class SourceFileList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SourceFileList) */ {
 public:
  SourceFileList();
  virtual ~SourceFileList();

  SourceFileList(const SourceFileList& from);

  inline SourceFileList& operator=(const SourceFileList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SourceFileList& default_instance();

  void Swap(SourceFileList* other);

  // implements Message ----------------------------------------------

  inline SourceFileList* New() const { return New(NULL); }

  SourceFileList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SourceFileList& from);
  void MergeFrom(const SourceFileList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SourceFileList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string sources = 1;
  int sources_size() const;
  void clear_sources();
  static const int kSourcesFieldNumber = 1;
  const ::std::string& sources(int index) const;
  ::std::string* mutable_sources(int index);
  void set_sources(int index, const ::std::string& value);
  void set_sources(int index, const char* value);
  void set_sources(int index, const char* value, size_t size);
  ::std::string* add_sources();
  void add_sources(const ::std::string& value);
  void add_sources(const char* value);
  void add_sources(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& sources() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_sources();

  // @@protoc_insertion_point(class_scope:SourceFileList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::std::string> sources_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_programdb_2eproto();
  friend void protobuf_AssignDesc_programdb_2eproto();
  friend void protobuf_ShutdownFile_programdb_2eproto();

  void InitAsDefaultInstance();
  static SourceFileList* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SourceFileList

// repeated string sources = 1;
inline int SourceFileList::sources_size() const {
  return sources_.size();
}
inline void SourceFileList::clear_sources() {
  sources_.Clear();
}
inline const ::std::string& SourceFileList::sources(int index) const {
  // @@protoc_insertion_point(field_get:SourceFileList.sources)
  return sources_.Get(index);
}
inline ::std::string* SourceFileList::mutable_sources(int index) {
  // @@protoc_insertion_point(field_mutable:SourceFileList.sources)
  return sources_.Mutable(index);
}
inline void SourceFileList::set_sources(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:SourceFileList.sources)
  sources_.Mutable(index)->assign(value);
}
inline void SourceFileList::set_sources(int index, const char* value) {
  sources_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:SourceFileList.sources)
}
inline void SourceFileList::set_sources(int index, const char* value, size_t size) {
  sources_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SourceFileList.sources)
}
inline ::std::string* SourceFileList::add_sources() {
  // @@protoc_insertion_point(field_add_mutable:SourceFileList.sources)
  return sources_.Add();
}
inline void SourceFileList::add_sources(const ::std::string& value) {
  sources_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:SourceFileList.sources)
}
inline void SourceFileList::add_sources(const char* value) {
  sources_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:SourceFileList.sources)
}
inline void SourceFileList::add_sources(const char* value, size_t size) {
  sources_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:SourceFileList.sources)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SourceFileList::sources() const {
  // @@protoc_insertion_point(field_list:SourceFileList.sources)
  return sources_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SourceFileList::mutable_sources() {
  // @@protoc_insertion_point(field_mutable_list:SourceFileList.sources)
  return &sources_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_programdb_2eproto__INCLUDED
