TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.c \
    src/jemalloc_cpp.cpp \
    src/arena.c \
    src/atomic.c \
    src/base.c \
    src/bitmap.c \
    src/ckh.c \
    src/ctl.c \
    src/extent_dss.c \
    src/extent_mmap.c \
    src/extent.c \
    src/hash.c \
    src/jemalloc.c \
    src/large.c \
    src/mb.c \
    src/mutex.c \
    src/nstime.c \
    src/pages.c \
    src/prng.c \
    src/prof.c \
    src/rtree.c \
    src/spin.c \
    src/stats.c \
    src/tcache.c \
    src/ticker.c \
    src/tsd.c \
    src/util.c \
    src/witness.c \
    src/zone.c \
    mmap_example.c

HEADERS += \
    include/jemalloc/jemalloc_defs.h \
    include/jemalloc/jemalloc_macros.h \
    include/jemalloc/jemalloc_mangle_jet.h \
    include/jemalloc/jemalloc_mangle.h \
    include/jemalloc/jemalloc_protos_jet.h \
    include/jemalloc/jemalloc_protos.h \
    include/jemalloc/jemalloc_rename.h \
    include/jemalloc/jemalloc_typedefs.h \
    include/jemalloc/jemalloc.h \
    include/jemalloc/internal/arena_externs.h \
    include/jemalloc/internal/arena_inlines_a.h \
    include/jemalloc/internal/arena_inlines_b.h \
    include/jemalloc/internal/arena_structs_a.h \
    include/jemalloc/internal/arena_structs_b.h \
    include/jemalloc/internal/arena_types.h \
    include/jemalloc/internal/assert.h \
    include/jemalloc/internal/atomic_externs.h \
    include/jemalloc/internal/atomic_inlines.h \
    include/jemalloc/internal/base_externs.h \
    include/jemalloc/internal/base_inlines.h \
    include/jemalloc/internal/base_structs.h \
    include/jemalloc/internal/base_types.h \
    include/jemalloc/internal/bitmap_externs.h \
    include/jemalloc/internal/bitmap_inlines.h \
    include/jemalloc/internal/bitmap_structs.h \
    include/jemalloc/internal/bitmap_types.h \
    include/jemalloc/internal/ckh_externs.h \
    include/jemalloc/internal/ckh_structs.h \
    include/jemalloc/internal/ckh_types.h \
    include/jemalloc/internal/ctl_externs.h \
    include/jemalloc/internal/ctl_structs.h \
    include/jemalloc/internal/ctl_types.h \
    include/jemalloc/internal/extent_dss_externs.h \
    include/jemalloc/internal/extent_dss_structs.h \
    include/jemalloc/internal/extent_dss_types.h \
    include/jemalloc/internal/extent_externs.h \
    include/jemalloc/internal/extent_inlines.h \
    include/jemalloc/internal/extent_mmap_externs.h \
    include/jemalloc/internal/extent_structs.h \
    include/jemalloc/internal/extent_types.h \
    include/jemalloc/internal/hash_inlines.h \
    include/jemalloc/internal/jemalloc_internal_decls.h \
    include/jemalloc/internal/jemalloc_internal_defs.h \
    include/jemalloc/internal/jemalloc_internal_defs.h.in \
    include/jemalloc/internal/jemalloc_internal_macros.h \
    include/jemalloc/internal/jemalloc_internal.h \
    include/jemalloc/internal/jemalloc_internal.h.in \
    include/jemalloc/internal/large_externs.h \
    include/jemalloc/internal/mutex_externs.h \
    include/jemalloc/internal/mutex_inlines.h \
    include/jemalloc/internal/mutex_structs.h \
    include/jemalloc/internal/mutex_types.h \
    include/jemalloc/internal/nstime_externs.h \
    include/jemalloc/internal/nstime_structs.h \
    include/jemalloc/internal/nstime_types.h \
    include/jemalloc/internal/pages_externs.h \
    include/jemalloc/internal/pages_types.h \
    include/jemalloc/internal/ph.h \
    include/jemalloc/internal/private_namespace.h \
    include/jemalloc/internal/private_unnamespace.h \
    include/jemalloc/internal/prng_inlines.h \
    include/jemalloc/internal/prng_types.h \
    include/jemalloc/internal/prof_externs.h \
    include/jemalloc/internal/prof_inlines.h \
    include/jemalloc/internal/prof_structs.h \
    include/jemalloc/internal/prof_types.h \
    include/jemalloc/internal/public_namespace.h \
    include/jemalloc/internal/public_unnamespace.h \
    include/jemalloc/internal/ql.h \
    include/jemalloc/internal/qr.h \
    include/jemalloc/internal/rb.h \
    include/jemalloc/internal/rtree_externs.h \
    include/jemalloc/internal/rtree_inlines.h \
    include/jemalloc/internal/rtree_structs.h \
    include/jemalloc/internal/rtree_types.h \
    include/jemalloc/internal/size_classes.h \
    include/jemalloc/internal/smoothstep.h \
    include/jemalloc/internal/spin_inlines.h \
    include/jemalloc/internal/spin_structs.h \
    include/jemalloc/internal/spin_types.h \
    include/jemalloc/internal/stats_externs.h \
    include/jemalloc/internal/stats_structs.h \
    include/jemalloc/internal/stats_types.h \
    include/jemalloc/internal/tcache_externs.h \
    include/jemalloc/internal/tcache_inlines.h \
    include/jemalloc/internal/tcache_structs.h \
    include/jemalloc/internal/tcache_types.h \
    include/jemalloc/internal/ticker_inlines.h \
    include/jemalloc/internal/ticker_structs.h \
    include/jemalloc/internal/ticker_types.h \
    include/jemalloc/internal/tsd_externs.h \
    include/jemalloc/internal/tsd_inlines.h \
    include/jemalloc/internal/tsd_structs.h \
    include/jemalloc/internal/tsd_types.h \
    include/jemalloc/internal/util_externs.h \
    include/jemalloc/internal/util_inlines.h \
    include/jemalloc/internal/util_types.h \
    include/jemalloc/internal/witness_externs.h \
    include/jemalloc/internal/witness_inlines.h \
    include/jemalloc/internal/witness_structs.h \
    include/jemalloc/internal/witness_types.h

DISTFILES += \
    include/jemalloc/internal/private_namespace.sh \
    include/jemalloc/internal/private_unnamespace.sh \
    include/jemalloc/internal/public_namespace.sh \
    include/jemalloc/internal/public_unnamespace.sh \
    include/jemalloc/internal/size_classes.sh \
    include/jemalloc/internal/smoothstep.sh \
    include/jemalloc/internal/private_symbols.txt \
    include/jemalloc/internal/public_symbols.txt
